services:
  - type: web
    name: CrescentHeights
    env: production
    plan: starter
    rootDir: web_app/templates/index.html  # specify the root directory here
    runtime: python # specify the runtime here
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: "production"
      - key: DB_URL
        value: "your-database-url"
      - key: SECRET_KEY
        value: "your-secret-key"
      - key: APP_SETTINGS
        value: "config.ProductionConfig"
